[theme]
<<<<<<< HEAD
backgroundColor = "#FFF5EE"  # Set background color using hex code  FFF5EE

[client]
showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8080
=======
backgroundColor = "#FFF5EE"  # Set background color using hex code  FFF5EE
>>>>>>> 6790240 (changed)
