credentials:
  usernames:
    laila:
      email: lailasafif@gmail.com
      name: Laila Safif
      password: abc # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - lailasafif@gmail.com